#!/usr/bin/env python
#
# calc - a very simple command line 4-operation calculator in python
# uses Python 2.x
import sys

p_name = "calc"
v_major = "0"
v_minor = "0"
v_patch = "1"
v_branch = "dev"
version = "%s %s.%s.%s-%s" % (p_name, v_major, v_minor, v_patch, v_branch)

valid_ops = ["-a", "-s", "-d", "-m"]

def print_help():
    print "usage: calc <operation> <operands>"
    print "operations (executed on operands left to right):"
    print "    -a : add operands together"
    print "    -s : subtract operands"
    print "    -d : divide operands"
    print "    -m : multiply operands"
    print "operands are space-separated integer or float strings"

def check(arg):
    if arg not in valid_ops:
        print_help()
        sys.exit(1)

def main(args):
    if len(sys.argv) == 2 and sys.argv[1] == "-v":
        print version
        sys.exit(0)
    elif len(sys.argv) == 2 and sys.argv[1] == "-h":
        print_help()
        sys.exit(0)
    elif len(sys.argv) < 4:
        print_help()
        sys.exit(1)
    op = sys.argv[1]
    nums = sys.argv[2:]
    check(op)
    ans = float(nums[0])
    if op == "-a":
        for n in nums[1:]:
            ans = ans + float(n)
    elif op == "-s":
        for n in nums[1:]:
            ans = ans - float(n)
    elif op == "-d":
        for n in nums[1:]:
            ans = ans / float(n)
    elif op == "-m":
        for n in nums[1:]:
            ans = ans * float(n)
    if ans == int(ans):
        print int(ans)
    else:
        print ans

if __name__ == '__main__':
    main(sys.argv)
